### ISSUE TITLE
Inconsistent error messages when (mis)using the selection() function

### ISSUE THREAD

**Issue by asianfilm** [keathley/norm#32]
There's some inconsistency in the error messages when mistakenly including a field in `selection()` that doesn't or no longer exists.

In a simple schema, the error message is fine. For example:

```elixir
defmodule Movie do
  use Norm

  defstruct title: "The Fly", year: 1986

  def s(),
    do:
      schema(%__MODULE__{
        title: spec(is_binary()),
        year: spec(is_integer())
      })

  def new(), do: %__MODULE__{}
end
```

When you try the following:

```elixir
Movie.new() |> conform(selection(Movie.s(), [:other])) 
```

You get the expected error:

```elixir
** (Norm.SpecError) key: :other was not found in schema:
```

However, when the code is more complex:

```elixir
defmodule Movie do
  use Norm

  defstruct directors: [], actors: []

  defmodule Person do
    use Norm

    defstruct name: ""

    def s(),
      do:
        schema(%__MODULE__{
          name: spec(is_binary())
        })
  end

  def s(),
    do:
      schema(%__MODULE__{
        actors: coll_of(Person.s()),
        directors: coll_of(Person.s())
      })

  def new(), do: %__MODULE__{}
end
```

When you try:

```elixir
Movie.new() |> conform(selection(Movie.s(), [:other])) 
```

You get a less helpful error message:

```elixir
** (FunctionClauseError) no function clause matching in Norm.SpecError.format/2    
    
    The following arguments were given to Norm.SpecError.format/2:
    
        # 1
        %Norm.Spec.Collection{
          opts: [distinct: false, min_count: 0, max_count: :infinity, into: []],
          spec: %Norm.Schema{
            specs: %{name: #Norm.Spec<is_binary()>},
            struct: Movie.Person
          }
        }
    
        # 2
        1
    
    Attempted function clauses (showing 5 out of 5):
    
        defp format({key, spec_or_schema}, i)
        defp format(atom, _) when is_atom(atom)
        defp format(str, _) when is_binary(str)
        defp format(%Norm.Spec{predicate: pred}, _)
        defp format(%Norm.Schema{specs: specs}, i)
    
    (norm) lib/norm/errors.ex:51: Norm.SpecError.format/2
    (norm) lib/norm/errors.ex:52: Norm.SpecError.format/2
    (elixir) lib/enum.ex:1340: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1964: Enum.map/2
    (norm) lib/norm/errors.ex:62: Norm.SpecError.format/2
    (norm) lib/norm/errors.ex:45: Norm.SpecError.msg/1
    (norm) lib/norm/errors.ex:39: Norm.SpecError.exception/1```

**Comment by keathley** [comment]
This is definitely a bug. I'll try to take a look at it soon.
