### ISSUE TITLE
SpecError from selections direct attention away from the problem

### ISSUE THREAD

**Issue by garthk** [keathley/norm#84]
```elixir
defmodule Extra do
  use Norm
  defstruct [:not_the_problem]
end

defmodule A do
  use Norm
  def assigns, do: schema(%{extra: schema(%Extra{})})
  def test, do: conform!(%{extras: %Extra{}}, selection(assigns(), :all))
end

A.test()
```
→
```
** (Norm.SpecError) key: :not_the_problem was not found in schema:
%{
  :not_the_problem => :
}

    (norm 0.12.0) lib/norm/core/selection.ex:56: Norm.Core.Selection.assert_spec!/2
    (norm 0.12.0) lib/norm/core/selection.ex:36: Norm.Core.Selection.select/3
    (norm 0.12.0) lib/norm/core/selection.ex:32: Norm.Core.Selection.select/3
    iex:70: A.test/0
```
→ wasting a whole bunch of time trying to figure out how `not_the_problem` could possibly be missing from a struct, when actually the problem is forgetting you meant the singular `extra` not the plural `extras`.

**Comment by garthk** [comment]
Aargh no wait…if you fix the typo it's the same error because the spec for `extra` doesn't declare any specs for the keys? I can see how this might be working as intended, but I can also see how I'm going to have a hard time with team members saying they're going back to `IO.inspect/2` because then at least they only need to figure out the behaviour of one piece of code.

**Comment by keathley** [comment]
This seems like a bug to me. Norm should be telling you that `extra` is missing from the map.
